var palavras = ['Amarelo','Amiga','Amor','Ave','Avião','Avó','Balão','Bebê','Bolo',
		'Branco','Cama','Caneca','Celular','Clube','Copo','Doce','Elefante',
		'Escola','Estojo','Faca','Foto','Garfo','Geleia','Girafa','Janela',
		'Limonada','Mãe','Meia','Noite','Óculos','ônibus','Ovo','Pai','Pão',
		'Parque','Passarinho','Peixe','Pijama','Rato','Umbigo','Acender',
		'Afilhado','Ardiloso','Áspero','Assombração','Asterisco','Basquete',
		'Caminho','Champanhe','Chiclete','Chuveiro','Coelho','Contexto',
		'Convivência','Coração','Desalmado','Eloquente','Esfirra','Esquerdo',
		'Exceção','Fugaz','Gororoba','Heterossexual','Horrorizado','Impacto',
		'Independência','Modernidade','Oftalmologista','Otorrinolaringologista',
		'Paralelepípedo','Pororoca','Prognóstico','Quarentena','Quimera',
		'Refeição','Reportagem','Sino','Taciturno','Tênue','Visceral','Afobado',
		'Amendoim','Banheiro','Caatinga','Cachorro','Campeonato','Capricórnio',
		'Catapora','Corrupção','Crepúsculo','Empenhado','Esparadrapo','Forca',
		'Galáxia','História','Magenta','Manjericão','Menta','Moeda','Oração',						'Paçoca','Palavra','Pedreiro','Pneumonia','Pulmão','Rotatória','Serenata',
		'Transeunte','Trilogia','Xícara', 'Axioma', 'Azulejo', 'Blitz', 'Catarro',
		'Coçar', 'Crespo', 'Cripta', 'Duplex', 'Fúcsia', 'Girar', 'Gnóstico',
		'Haicai', 'Hera', 'Hífen', 'Icterícia', 'Indigno', 'Intrigante', 'Jazz',
		'Linfa', 'Marfim', 'Ônix', 'Psique', 'Quartzo', 'Quiz', 'Quorum', 'Tonto',
		'Topázio', 'Torpor', 'Valsa', 'Vaporizar', 'Vertiginoso', 'Vicissitude',
		'Vórtice', 'Xilofone'];